### ISSUE TITLE
plugin should be called Mercury?

### ISSUE THREAD

**Issue by ariehkovler** [Civcraft/Mercury#1]

**Comment by ttk2** [comment]
probably, misspelling is easy

**Comment by WildWeazel** [comment]
That was my first thought too. It can be changed easily enough.
e: nevermind, already done

**Comment by rourke750** [comment]
It is called Mercury???

**Comment by erocs** [comment]
Nah, Freddy.

**Comment by ghost** [comment]
Done. It will apply on server restart
