### ISSUE TITLE
Inversed Player hashmap in MercuryAPI

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/Mercury#10]
The onlineAllServers hashmap in MercuryAPI is actually built up inversed than what all the documentation and the methods suggest.

I tried here https://github.com/Civcraft/NameLayer/pull/139/files#diff-c300f2feb92fc77055b0c48b254f73f2R166 to get all players via Mercury, but when testing this I realized, that not the names of all players are returned, but instead the names of the shards.

And because this method is returning a keyset here: https://github.com/Civcraft/Mercury/blob/master/src/vg/civcraft/mc/mercury/MercuryAPI.java#L83 , which makes sense in the context of everything else there, but apparently delivers, what are supposed to be entries, the whole hashmap is apparently being built up inversed.

This is not an issue within the MercuryAPI class itself, but whatever class is actually adding players by using the API probably has some arguments inversed.

**Comment by rourke750** [comment]
Fixes https://github.com/Civcraft/Mercury/commit/571e934602f1a0d64b5b02fc01ae8ec4dff8b636
