### ISSUE TITLE
Wrong message handling

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/Mercury#11]
Finally nailed down the CivChat issue to this after 2 hours of outputting debug messages.

Most of the messages created by Mercury are of the format "data1|data2|data3". To process that simply String.split("|") is used, but the problem with that is that java interprets "|" as a logical or and not a literal, so what it does instead is basically: String.split(""|""), which means that for example here:

https://github.com/Civcraft/Mercury/blob/master/src/vg/civcraft/mc/mercury/MercuryBukkitListener.java#L90

everything is messed up. Instead of properly splitting up the message and finding the reason, it dissects the string into single characters, which keeps anything here from working. Either find a way to escape "|" or use another character to split up the messages.

**Comment by ProgrammerDan** [comment]
http://stackoverflow.com/questions/3842537/grails-splitting-a-string-that-contains-a-pipe

"|" == "\|"

**Comment by ttk2** [comment]
so do we have a fix for this yet?

**Comment by rourke750** [comment]
@ProgrammerDan So I just need to change that line to a | right?  Only there as well right?

**Comment by erocs** [comment]
I swear I fixed all these. I'll deal with it...

**Comment by ProgrammerDan** [comment]
Well it's just Java string escaping @Rourke750. You'd need to replace the single pipe with an escaped escape followed by the pipe -- "\\|"

**Comment by erocs** [comment]
Fix pushed. I had fixed MiscLog and forgot this for Mercury.  >_<

**Comment by Maxopoly** [comment]
Fixed by https://github.com/Civcraft/Mercury/commit/93e2d54afa0a4ca5b4389cc8ea60af54dddeead5
