### ISSUE TITLE
Shard ping timeout

### ISSUE THREAD

**Issue by erocs** [Civcraft/Mercury#18]
Send a ping every 60 seconds. Expect a server's ping within 130 seconds. Alter the ping task to only run every second.

@rourke750

**Comment by erocs** [comment]
Pretty please configurable at runtime.

**Comment by rourke750** [comment]
So for configuration values anything too high a player will get DC before.
Ill make both configurable and then you can play with it.

**Comment by rourke750** [comment]
https://github.com/Civcraft/Mercury/commit/857b07a1137941c6bb14026ae133640fec3dd8f0
